@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYwMzIwMjQ4NywiZXhwIjoxNjAzMjA2MDg3LCJuYmYiOjE2MDMyMDI0ODcsImp0aSI6IjNEWUNUTWtnZ0hoQlVFQ3kiLCJzdWIiOjEsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJpZCI6MX0.kgy2rsTYaNgFmkgGS_3T4fN386Howq-aqm7Qv8RMIuk

@baseUrl = http://localhost:8000/api

GET {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###

GET {{baseUrl}}/products/find/6
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###

POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"name": "Produto Fake",
	"price": 29.99,
    "description": "Um produto feito para você",
	"category": 1
}

###
