@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9sb2dpbiIsImlhdCI6MTYwMzIwNTEyNCwiZXhwIjoxNjAzMjA4NzI0LCJuYmYiOjE2MDMyMDUxMjQsImp0aSI6Im10RnVodFVMMFVmWXloWVAiLCJzdWIiOjIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjciLCJpZCI6Mn0.A38iOLJl3CSH3p0W2_o2M5nE9QZ2G_t6j_LbEvd2_Ts

@baseUrl = http://localhost:8000/api

GET {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###

GET {{baseUrl}}/users/find/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###

POST {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
	"name": "Karolina",
	"email": "karol@gmail.com",
    "password": "123456"
}

###
